### ISSUE TITLE
No hits found using the example IROA mzML file and database

### ISSUE THREAD

**Issue by SouraTR** [pattilab/DecoID#1]
I am trying to use the package as is with `IROA_P1-6_DIA_test_pos1.mzML` and `IROA_updated_NCE40.db` with a properly formatted peak-file. While running the package is populating the `x_scanInfo.csv` file but I am not getting any identifications (`x_decoID.csv` file is empty except the header)

![image](https://user-images.githubusercontent.com/51744901/160559916-62c6a732-1b36-4d4a-ba8d-7c7cc142d853.png)

Here is the code below
```from DecoID.DecoID import DecoID

#sets database to use
libFile = "IROA_updated_NCE40.db"

# #mzCloud key if necessary
key = "none"
mzCloudLib = "reference"

#number of parallel processes to use
numCores = 4

#filename of query MS/MS data
file = "IROA_P1-6_DIA_test_pos1.mzML"

#filename of peak list
peakFile = "peak-file-filt.csv"

#set parameters
usePeaks = True
DDA = False #data is DIA
massAcc = 10 #ppm tolerance
fragThresh= 0.01 #require non-zero dot product threshold
offset = .5 #half of isolation window width. Only for non-thermo data
useIso = False #use predicted M+1 isotopolgoue spectra
threshold = 0 #minimum dot product for reporting
lam = 50.0 #LASSO parameter
rtTol = 0.5 #retention time tolerance for database, inf means ignore RT
fragCutoff = 1000 #intensity threshold for MS/MS peaks

if __name__ == '__main__':

    #create DecoID object
    decID = DecoID(libFile, mzCloudLib, numCores, api_key=key)

    #read in data
    decID.readData(file, 2, usePeaks, DDA, massAcc,offset)
    decID.searchSpectra("y", lam , fragThresh, useIso, threshold,rtTol=rtTol)```

**Comment by e-stan** [comment]
Hello, have you installed the latest version of DecoID (v0.3.3)? From your output, it looks like the version is out of date. To better help resolve your issue, can you also please send the peak file that you used? When running the example code (DecoID/examples/exampleUsageDIA.py) with the IROA database, which is similar to what you attached but uses the peak file (DecoID/exampleData/IROA_p1-6_peak_table_pos_v3.csv, I was not able to reproduce your error and it resulted in a populated _decoID.csv file.

**Comment by e-stan** [comment]
I noticed one issue in your code. The second to last line should be:    

`decID.readData(file, 2, usePeaks, DDA, massAcc,offset,peakDefinitions=peakFile,frag_cutoff=fragCutoff)`

You did not provide the peakDefinitions argument, which is required for DIA data.

**Comment by SouraTR** [comment]
Hey Ethan, thankyou so much this resolved my issue!
