### ISSUE TITLE
Running not responding

### ISSUE THREAD

**Issue by ray1919** [pattilab/DecoID#2]
I installed DecoID v0.3.3 in Ubuntu 18.04, Python 3.7.13 / 3.8.1。
Running `exampleUsage.py` on `exampleData` had no problem, however it will display warnings like

```
/home/zhaorui/anaconda3/envs/py3.7/lib/python3.7/site-packages/DecoID/DecoID.py:91: RuntimeWarning: invalid value encountered in double_scalars
  if np.isinf(np.power(np.float(maxSpec/maxSpec),2)) or np.isnan(np.power(np.float(maxSpec/maxSpec),2)):
/home/zhaorui/anaconda3/envs/py3.7/lib/python3.7/site-packages/DecoID/DecoID.py:251: RuntimeWarning: divide by zero encountered in true_divide
  differences =  np.subtract(flatten(originalSpectra),flatten(solvedSpectraTotal))/numComponents
/home/zhaorui/anaconda3/envs/py3.7/lib/python3.7/site-packages/DecoID/DecoID.py:251: RuntimeWarning: invalid value encountered in true_divide
  differences =  np.subtract(flatten(originalSpectra),flatten(solvedSpectraTotal))/numComponents
/home/zhaorui/anaconda3/envs/py3.7/lib/python3.7/site-packages/DecoID/DecoID.py:251: RuntimeWarning: divide by zero encountered in true_divide
  differences =  np.subtract(flatten(originalSpectra),flatten(solvedSpectraTotal))/numComponents
/home/zhaorui/anaconda3/envs/py3.7/lib/python3.7/site-packages/DecoID/DecoID.py:251: RuntimeWarning: invalid value encountered in true_divide
  differences =  np.subtract(flatten(originalSpectra),flatten(solvedSpectraTotal))/numComponents
/home/zhaorui/anaconda3/envs/py3.7/lib/python3.7/site-packages/DecoID/DecoID.py:166: RuntimeWarning: invalid value encountered in double_scalars
  val = num/denom
```

And while I test exampleUsage.py on my own data converted using msconvert, the command line DecoID will run for a while
and just stop running without any errors, nor exit. The output file `_decoID.csv` has an incomplete last line.

I compared the structure of both mzML files, found them just quite like, except my converted mzML is about 1.5X larger than the `IROA_P1-6_ddMS2_pos_1Da.mzML`.

I wonder whether you could give me some help. Thank you for your time.

**Comment by e-stan** [comment]
Hello,

The warning messages you see are normal and handled internally in the software. Regarding your data, is this DIA or DDA data? Did you provide a different peak list? Are any other parameters changes in exampleUsage.py? If you could upload your data and peak list, that would be helpful for troubleshooting. Thank you for trying DecoID!

**Comment by ray1919** [comment]
It is a DDA data. When I provide a peak list computed from xcms workflow, DecoID only return a few results, less than 10.
[1_decoID.csv](https://github.com/pattilab/DecoID/files/9188525/1_decoID.csv)
[peak_table.csv](https://github.com/pattilab/DecoID/files/9188526/peak_table.csv)

the parameters are all default

```
#parameters

#mzML file dir
datadir = "./"

#db file path
libFile = "../../../MoNA-export-LC-MS-MS_Spectra.db"

#number of parallel processes to use
numCores = 16

#filename of peak list
peakfile = "peak_table.csv"

#set parameters
usePeaks = True #use MS1 data or not
DDA = True #data is DDA
massAcc = 10 #ppm tolerance
fragThresh= 0.01 #require non-zero dot product threshold
offset = .5 #half of isolation window width. Only for non-thermo data
useIso = True #use predicted M+1 isotopolgoue spectra
threshold = 0 #minimum dot product for reporting
lam = 5.0 #LASSO parameter
rtTol = float("inf") #retention time tolerance for database, inf means ignore RT
fragCutoff = 1000 #intensity threshold for MS/MS peaks
numHits = 3 #number of hits to keep for each feature
```

I think there should be hundreds of metas be identified. What is wrong with my test?

**Comment by e-stan** [comment]
Thank you for providing more details. From looking at your peak table, it looks like the retention times are given in seconds. These need to be converted to minutes. You also may want to change the massAcc parameter, depending on the instrument you are using. Hopefully this resolves your issue.

**Comment by ray1919** [comment]
Thank you for your help. Having the right rt in minutes, it works. 

I Still have problem with mutithreading. When I run with multithreads (less than my physical threads), the script will stop running in 2~3 hours after launch. However running with single threads do not have such problem.

And one more question: How could I search with multipile databases or make my own dbs from HDMB xml file?

**Comment by e-stan** [comment]
I am glad that the RT change was able to get you your expected results. Regarding the multi-processing, I am not sure what is causing the crash. I have not done extensive testing of DecoID on unix systems, but I have not encountered this issue before. Are you wrapping the code in the script with: if __name__ == "__main__"? I know that can cause issues if not included. DeocID is also using multiprocessing not multithreading, so numCores should be set to be less than or equal to the number of physical CPU cores on the machine. 

To search with multiple databases, you can simply process the data with multiple databases independently and then combine the results with the combine_results_auto_annotate function, see https://github.com/pattilab/DecoID/blob/master/examples/search_multiple_files_combine_results.py for an example of how to use this function. If you would like to make your own database, you can make a .msp library. A description of this file can be found at https://decoid.readthedocs.io/en/latest/examples.html#database
